### ISSUE TITLE
unwrapping `params.images.get` panics, no matter what I do

### ISSUE THREAD

**Issue by marijanp** [FraserLee/bevy_sprite3d#26] opened 2024-10-30 15:04 UTC
I'm not sure how Sprite3dParams::images` gets populated. simply following the examples ends up failing.
https://github.com/FraserLee/bevy_sprite3d/blob/ce57326ff63b1dae99cd2595422672bc82b22325/src/lib.rs#L264

**Comment by FraserLee** [comment] 2024-11-05 17:43
I'm closing this for now as a likely duplicate of #5 . If the solutions there don't work, feel free to reopen. Cheers

**Closed by FraserLee** 2024-11-05 17:43 UTC
